### ISSUE TITLE
EndlessScrolling isn't working

### ISSUE THREAD

**Issue by jayathu** [jayathu/NewYorkTimesArticleSearch-Project1#1]
I am just beginning to implement event handlers of EndlessRecyclerViewScrollListener. Please take a look at SearchActivity.java. Even though I have implemented the callback, I don't think this is getting called when I scroll the page. I am obviously doing something wrong but have been struggling to spot it for the past couple of hours. Someone taking a look at it is greatly appreciated!

@codepathreview @codepath
Thanks

**Comment by nesquena** [comment]
Check out [problem #2](http://courses.codepath.com/courses/intro_to_android/unit/2#!hints) first bullet in the hints. Hint: https://github.com/jayathu/NewYorkTimesArticleSearch-Project1/blob/master/NYTimesSearch/app/src/main/java/project/codepath/nytimessearch/activities/SearchActivity.java#L159

**Comment by jayathu** [comment]
Ah! How did I miss that.....good reminder to check out the hints section :) Thanks so much!

**Comment by jayathu** [comment]
How do I clear the adapter though? I can't see any methods that seem to do that such as adapter.clear() type of a thing. And if I had to do this within the adapter class, is there a callback I can override? and how exactly do I clear the adapter from the class?

**Comment by nesquena** [comment]
With RecyclerView adapters, you can clear the array list directly and then notify the adapter of the change.

**Comment by jayathu** [comment]
Thanks!

On Sat, Feb 13, 2016 at 10:34 PM, Nathan Esquenazi <notifications@github.com
