### ISSUE TITLE
Struggling with Search Filters

### ISSUE THREAD

**Issue by jayathu** [jayathu/NewYorkTimesArticleSearch-Project1#2]
I have been struggling with properly storing and retrieving search filters (from the Settings activity) for my queries. Could you please take a look at models.QueryFilters.java class (which is a Parcelable), Settings.java and SearchActivity.java class? Just look at my latest commits and give me your thoughts. It's half baked and I am getting into a rabbit hole, failing to find a cleaner solution.

Also, I wonder how should my final url look like? And how can I persist my settings values?

@codepathreview @codepath

**Comment by nesquena** [comment]
> I have been struggling with properly storing and retrieving search filters (from the Settings activity) for my queries. 

Could you be a bit more specific about what you are struggling on or what's not working? Conceptually I think you have it. Java object which contains all the filters specified, passed back and forth between search and settings through an intent.

> Also, I wonder how should my final url look like?

Looks like: http://api.nytimes.com/svc/search/v2/articlesearch.json?api-key=KEY&q=android&begin_date=02142016. In essence you want to iterate through the filters and then append each one as a parameter to your request. 

> And how can I persist my settings values?

Persisting them across runs of the app is not a required story (only persisting for subsequent searches within a single session) but you can do so using [SharedPreferences](http://guides.codepath.com/android/Persisting-Data-to-the-Device#shared-preferences).

**Comment by jayathu** [comment]
The struggle is with the various strings that I append into the news_desk value. Right now I am doing something like this: 

 if(cb_option_politics.isChecked()){
            news_desk_values += "\"Politics\"";
        }
        if(cb_option_Sports.isChecked()) {
            news_desk_values += " \"Sports\"";
        }
        if(cb_option_tech.isChecked()){
            news_desk_values += " \"Technology\"";
        }

However, when I come back to the Settings Activity, its a nightmare to manually parse news_desk_values to figure out which checkboxes (corresponding to the news_desk) to mark as selected/not selected.

**Comment by nesquena** [comment]
Maybe store those items in filters object as an array so it's easier to parse later?

**Comment by jayathu** [comment]
I just refactored to keep everything as boolean properties (hardcoded values for different fields) which is obviously an ugly and hacky way of doing it but at least in the interest of time, it works for me :-)
